theme: jekyll-theme-modernist
baseurl: /beta/
title: PostgreSQL.TW
description: 我在台灣，我用PostgreSQL
show_downloads: false
timezone: Asia/Taipei
plugins:
  - jemoji

collections:
  backgrounds:
  pages:
    output: true
    permalink: /beta/:name
